### ISSUE TITLE
CI segfaults on FreeBSD

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/libc#1489]
CI has started to segfault on FreeBSD since the latest nightly. 

[This build passed](https://cirrus-ci.com/task/5140254878597120) with  nightly-x86_64-unknown-freebsd 1.39.0 (760226733 2019-08-22)
[This build failed](https://cirrus-ci.com/task/6196089037783040) with nightly-x86_64-unknown-freebsd 1.39.0 (9eae1fc0e 2019-08-23)

The segfault is triggered by the build.rs of `rand_pcg v0.1.2`  and `rand_chacha v0.1.1` (cc @dhardy), which AFAICT only call `autocfg` (cc @cuviper ). There was an update of `autocfg` recently so initially I thought that might be it, but it seems that the builds were working correctly with that update, so AFAICT neither `autocfg` nor `rand` are at fault here (cc @mati865 @asomers ).  Looking at the recently merged PRs in rust-lang/rust, I don't see any suspicious one.

**Comment by mati865** [comment]
I'm mostly unavailable until Monday/Tuesday.
Without backtrace it'll be hard to find the reason. Maybe you could run GDB on that CI or even locally?

**Comment by gnzlbg** [comment]
I have a minimal reproducer now: https://github.com/rust-lang/libc/pull/1490

```toml
# Cargo.toml
[package]
name = "test_failure"
version = "0.1.0"
authors = ["The Rust Project Developers"]
license = "MIT OR Apache-2.0"

[build-dependencies]
autocfg = "0.1"
```

and `build.rs`:

```rust
extern crate autocfg;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    let ac = autocfg::new();
    ac.emit_rustc_version(1, 26);
}
```

---

This fails on FreeBSD12, but not on FreeBSD11. A backtrace of the segfault would be nice.
