### ISSUE TITLE
Question: where is timer_create?

### ISSUE THREAD

**Issue by TomzBench** [rust-lang/libc#2305]
Hello -

I wasn't sure where to ask so I opened this issue. Sorry if this is not a good venue for a simple questions.  The rust-lang discord doesn't allow chat and wasn't sure where else to go.

But anyway - I pulled in the libc crate to get access to the `timer_create()` api and perhaps i am missing a feature flag or am having a configuration issue, because I see the binding in the source code but I cannot use it.

I'm using fedora34, below is my cargo.toml
```toml
[package]
name = "blah"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

```
